services:
  db:
    image: postgres:15-alpine
    container_name: covid_db_container
    env_file:
      - .env
    environment:
      POSTGRES_DB: covid_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d covid_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    build: ./mlflow
    container_name: mlflow_tracking_server
    env_file:
      - .env
    ports:
      - "5001:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/mlflow_db
      --default-artifact-root /artifacts
      --host 0.0.0.0
      --port 5000
    volumes:
      - mlflow_data:/artifacts
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    container_name: covid_app_runner
    user: appuser 
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_started
    volumes:
      - .:/app
      - mlflow_data:/artifacts
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/covid_db"
      MLFLOW_TRACKING_URI: "http://mlflow:5000"

volumes:
  postgres_data:
  mlflow_data:
